name: Publish backend
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    permissions: write-all
    name: Publish binaries
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Build binaries
      run: cd server && npm install && npm run build
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        release_name: ${{ github.ref }}-Backend
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./server/dist/index.js
        asset_name: App
        tag: ${{ github.ref }}
        overwrite: true
        body: "Amazing trirea release!"